### ISSUE TITLE
Returns Board ID with Invalid Difficulty Level

### ISSUE THREAD

**Issue by AkshayVemulapalli** [CSAllenISDClassroom/sudokuserver-acid-dragons-1#35]
The parameters for difficulty are currently easy, medium, hard, and hell, but if I put a URL with the difficulty VeryHard it still gives me an ID instead of returning an error.

This is the URL I used for my POST request: https://codermerlin.com/vapor/vivek-maranganti/games?difficulty=VeryHard

**Comment by Sahil-Sheth** [comment]
As a class, we had not decided on the difficulty levels so we had extra difficulty levels such as very easy and very hard. As of right now, we have removed the extra difficulty levels and only have easy, medium, hard, and hell

**Comment by Tariq-Mahamid** [comment]
Fixed.
