### ISSUE TITLE
Cell and Box index issue

### ISSUE THREAD

**Issue by Vivek-Maranganti** [CSAllenISDClassroom/sudokuserver-acid-dragons-1#40]
When box or cell index goes over 8, the entire server crashes without returning a board.

URL used: "https://codermerlin.com/vapor/vivek-maranganti/games/4696732637138131058/cells/9/9"

**Comment by Sahil-Sheth** [comment]
This has been fixed. It will now give an error saying to input a box index or cell index from 0-8. It will not crash the server. Also, make sure that you are using the main branch and not the others since the main branch has the most up-to-date working code.
