### ISSUE TITLE
Miscellaneous request parameters work

### ISSUE THREAD

**Issue by AirOnCruise** [CSAllenISDClassroom/sudokuserver-acid-dragons-1#42]
Examples of acceptable parameters for POST, GET, and PUT are not stated anywhere. When creating a POST or GET request, it seems to work regardless of a random input, ex. "difficulty=ehuefhue" or "filter=grrgrghrh" work for their respective requests.

**Comment by NatLark** [comment]
I attempted the same thing by putting random parameters for filter and difficulty. Inputs such as "difficulty=aaaaaaaaa" or "difficulty=123" give an ID.

**Comment by Tariq-Mahamid** [comment]
Fixed.
