### ISSUE TITLE
Usage of `null` to clear cell

### ISSUE THREAD

**Issue by agarmu** [CSAllenISDClassroom/sudokuserver-acid-dragons-1#47]
Upon attempting to PUT with the following body on an otherwise valid, cell:
```json
{
"value": null
}
```
The following response is returned:
```json
{"error":true,"reason":"Value of type 'Int' required for key 'value'."}
```

However, no such error should be returned and the cell should simply be cleared of any values

**Comment by Tariq-Mahamid** [comment]
To remove a cell pass nothing in the body
